version: '3.8'

services:
  stable-diffusion-api:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    ports:
      - "8080:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./cache:/root/.cache  # Cache models to avoid re-downloading
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]