version: '3.8'

services:
  stable-diffusion-api:
    build: .
    ports:
      - "8080:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./cache:/root/.cache  # Cache models to avoid re-downloading
    restart: unless-stopped
    mem_limit: 4g  # Limit memory usage
    cpus: 2.0      # Limit CPU usage